- name: install dependance
  yum:
    name: {{ item }}
    state: present
    update_cache: "no"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: Import Docker repository key
  rpm_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: no
    enabled: yes
    description: docker repo
- name: Install (or update) docker package
  yum:
    name: docker-ce-18.03.0.ce
    state: present
    enablerepo: docker
- name: Enable docker
  service:
    name: docker
    enabled: yes
- name: Stop docker
  service:
    name: docker
    state: stopped
- name: Start docker
  service:
    name: docker
    state: started
