- name: install dependance
  apt:
    name: {{ item }}
    force: "yes"
    state: present
    update_cache: "no"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Import Docker repository key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    update_cache: "yes"
    state: present
- name: Install (or update) docker package
  yum:
    name: docker-ce=18.03.0~ce-0~ubuntu
    force: "yes"
    state: present
    update_cache: "no"
- name: Stop docker
  service: name=docker state=stopped
- name: Start docker
  service: name=docker state=started
